# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [pre-commit, pre-push, commit-msg]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
      - id: file-contents-sorter
        files: "\\.Rbuildignore$"
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
          man/.*|
          tests/testthat/_snaps/.*\.md|
          )$

  - repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: "0.1.3"
    hooks:
      - id: tidy-gitignore

ci:
  autoupdate_schedule: monthly
