# documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: false
install: travis_wait 30 mvn install

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

r_binary_packages:
  - stringi
  - magrittr
  - curl
  - jsonlite
  - Rcpp
  - RcppEigen
  - openssl
  - utf8
  - gss
  - haven
  - minqa
  - mvtnorm
  - nloptr
  - SparseM
  - httpuv
  - markdown
  - sem
  - readxl
  - openxlsx
  - pander
  - lme4
  - psych
  - git2r
  - data.table
#  - rlang
#  - bindrcpp
#  - purrr
#  - tidyr
#  - dplyr
#  - readr

r_packages:
  - rlang
  - bindrcpp
  - purrr
  - tidyr
  - dplyr
  - readr
  - covr
  - ggthemes
  - jcolors
  - oompaBase
  - palr
  - coin
  - jmv
  - sjstats
  - WRS2
  - scico
  - viridisLite

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
