# documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
dist: trusty
cache: packages
latex: true
warnings_are_errors: true

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true
    - MAKEFLAGS="-j 2"

#r_check_args: "--run-dontrun"



notifications:
  email:
  on_success: change
  on_failure: change

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      r_binary_packages:
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - RcppEigen
        - openssl
        - utf8
        - gss
        - haven
        - minqa
        - mvtnorm
        - nloptr
        - SparseM
        - httpuv
        - markdown
        - sem
        - readxl
        - openxlsx
        - pander
        - lme4
        - psych
        - git2r
        - data.table
        - rjags
        - StanHeaders
        - rstan
        - LaplacesDemon
        - logspline
        - metaBMA
      r_packages:
        - rlang
        - bindrcpp
        - purrr
        - tidyr
        - dplyr
        - readr
        - ggthemes
        - jcolors
        - oompaBase
        - palr
        - coin
        - jmv
        - sjstats
        - WRS2
        - scico
        - viridisLite
        - bridgesampling
        - rstantools
        - BH
        - remotes
      r_github_packages:
        - jimhester/lintr
        - r-lib/covr
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      r: devel
      r_binary_packages:
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - RcppEigen
        - openssl
        - utf8
        - gss
        - haven
        - minqa
        - mvtnorm
        - nloptr
        - SparseM
        - httpuv
        - markdown
        - sem
        - readxl
        - openxlsx
        - pander
        - lme4
        - psych
        - git2r
        - data.table
        - rjags
        - StanHeaders
        - rstan
        - LaplacesDemon
        - logspline
        - metaBMA
      r_packages:
        - rlang
        - bindrcpp
        - purrr
        - tidyr
        - dplyr
        - readr
        - ggthemes
        - jcolors
        - oompaBase
        - palr
        - coin
        - jmv
        - sjstats
        - WRS2
        - scico
        - viridisLite
        - bridgesampling
        - rstantools
        - BH
        - remotes
      r_github_packages:
        - jimhester/lintr
        - r-lib/covr
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
