language: r
r:
  - release
#  - devel

latex: true
warnings_are_errors: TRUE

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

# cache:
#   - packages
#   - ccache

r_binary_packages:
  - magrittr
  - curl
  - jsonlite
  - rstan
  - Rcpp
  - RcppEigen
  - openssl
  - utf8
  - gss
  - haven
  - minqa
  - mvtnorm
  - nloptr
  - SparseM
  - httpuv
  - markdown
  - pander
  - git2r
  - rlang
  - bindrcpp
  - tidyr
  - dplyr
  - rstantools
  - bridgesampling
  - BH
  - stringi
  - BayesFactor
  - metaBMA
  - coda
  - coin
  - multcomp
  - pbkrtest
  - mc2d
  - data.table
  - lme4
  - lmerTest
  - GGally
  - emmeans
  - ggrepel
  - metaplus
  - fastGHQuad

r_packages:
  - remotes
  - knitr
  - rmarkdown
  - ipmisc
  - afex
  - effectsize
  - insight
  - ggcorrplot

r_github_packages:
  - jimhester/lintr
  - r-lib/covr

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
