# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false
fortran: true

# Note: http test servers are flaky and we want to minimze false positives
# so we skip examples and vignettes (but not unit tests) on OS X.

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

      r_binary_packages:
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - bindrcpp
        - RcppEigen
        - rpf
        - openssl
        - rlang
        - igraph
        - utf8
        - gss
        - haven
        - XML
        - data.table
        - matrixStats
        - rgl
        - dplyr
        - purrr
        - tidyr
        - readr
        - minqa
        - mvtnorm
        - nloptr
        - SparseM
        - lme4
        - httpuv
        - markdown
        - OpenMx
        - sem
        - readxl
        - openxlsx
        - pander
        - minpack.lm
        - StanHeaders

        # "These installs will be faster than source installs, but may not always be the most recent version"
        # https://docs.travis-ci.com/user/languages/r/#Additional-Dependency-Fields

    - os: osx
      osx_image: xcode9.3beta
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew install curl
        - brew link --force curl
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode7.3
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr
  - devtools

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
