# Run vignettes with `options(warn = 2)` to fail on warnings
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-vignette-warnings

jobs:
  check-vignette-warnings:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1.6.1"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "devel"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          pak-version: devel
          extra-packages: |
            local::.

      - name: Build vignettes
        run: |
          options(crayon.enabled = TRUE, warn = 2L)
          vignettes <- fs::dir_ls("vignettes/", glob = "*.Rmd", recurse = TRUE)
          purrr::walk(vignettes, rmarkdown::render)
        shell: Rscript {0}
