# Run tests with `options(warn = 2)` to fail on test warnings
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-test-warnings

jobs:
  check-test-warnings:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "devel"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: |
            local::.

      - name: Run Tests
        run: |
          options(crayon.enabled = TRUE, warn = 2L)
          if (Sys.getenv("_R_CHECK_FORCE_SUGGESTS_", "") == "") {
            Sys.setenv("_R_CHECK_FORCE_SUGGESTS_" = "false")
          }
          testthat::test_dir("tests")
        shell: Rscript {0}
