# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, master]

name: lint-changed-files

jobs:
  lint-changed-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: "TRUE"
          needs: check
          extra-packages: |
            any::gh
            any::purrr
            r-lib/lintr
            local::.

      - name: Extract and lint files changed by this PR
        run: |
          options(crayon.enabled = TRUE)
          library(lintr)
          files <- gh::gh("GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")
          changed_files <- purrr::map_chr(files, "filename")
          all_files <- list.files(recursive = TRUE)
          exclusions_list <- as.list(setdiff(all_files, changed_files))
          # lintr config in `.lintr` file
          lint_package(exclusions = exclusions_list)
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
