on:
  pull_request:
    branches: [main, master]

name: pre-commit

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - uses: stefanzweifel/git-auto-commit-action@v6.0.1
